FROM openjdk
WORKDIR usr/lib
ADD ./target/BEJ-C2-S3-Restful-MongoDb-Challenge-Track-0.0.1-SNAPSHOT.jar /usr/lib/BEJ-C2-S3-Restful-MongoDb-Challenge-Track-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "BEJ-C2-S3-Restful-MongoDb-Challenge-Track-0.0.1-SNAPSHOT.jar"]